version: "3.3"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=lab34db
      - POSTGRES_USER=lab34dbuser
      - POSTGRES_PASSWORD=12345678
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=lab34db
      - POSTGRES_USER=lab34dbuser
      - POSTGRES_PASSWORD=12345678
    depends_on:
      - db

